[pytest]
addopts = --import-mode=importlib
testpaths =
    tests
    Resources/economics/edexcel-a/generator/tests
    Resources/economics/aqa/generator/tests
    Resources/economics/ocr/generator/tests
    Resources/computer-science/aqa/generator/tests
    Resources/computer-science/ocr/generator/tests
    Resources/business/aqa/generator/tests
    Resources/accounting/aqa/generator/tests
pythonpath =
    .
    Resources/economics/edexcel-a/generator
    Resources/economics/aqa/generator
    Resources/economics/ocr/generator
    Resources/computer-science/aqa/generator
    Resources/computer-science/ocr/generator
    Resources/business/aqa/generator
    Resources/accounting/aqa/generator
