from __future__ import annotations

from copy import deepcopy

from pastpapergen.models import PaperConfig, SectionConfig


_BUILTIN_CONFIGS: dict[str, PaperConfig] = {
    "paper_1": PaperConfig(
        id="paper_1",
        code="9EC0/01",
        title="Markets and Business Behaviour",
        allowed_themes={1, 3},
        duration_minutes=120,
        total_marks=100,
        sections=[
            SectionConfig(
                name="A",
                title="Multiple-choice and short-answer questions",
                marks=25,
                answer_marks=25,
                question_marks=[5, 5, 5, 5, 5],
                command_words=["mixed", "mixed", "mixed", "mixed", "mixed"],
                part_marks=[[4, 1], [4, 1], [4, 1], [4, 1], [4, 1]],
                part_command_words=[
                    ["explain", "mcq"],
                    ["explain", "mcq"],
                    ["draw", "mcq"],
                    ["explain", "mcq"],
                    ["explain", "mcq"],
                ],
                stimulus_kinds=[
                    "ped_data_table",
                    "pes_data_table",
                    "market_share_bar_chart",
                    "marginal_utility_table",
                    "opportunity_cost_ppc_table",
                    "business_objective_context",
                    "xed_context",
                    "imperfect_information_context",
                    "minimum_wage_context",
                    "cost_revenue_graph",
                    "data_table",
                    "market_diagram",
                    "context_extract",
                    "bar_chart",
                    "line_graph",
                    "index_number_chart",
                    "elasticity_data_table",
                    "concentration_ratio_table",
                    "shutdown_cost_table",
                    "wage_rate_table",
                    "contestability_barrier_table",
                    "demand_shift_graph",
                    "supply_shift_graph",
                    "tax_subsidy_diagram",
                    "tax_incidence_diagram",
                    "externality_diagram",
                    "consumer_surplus_diagram",
                    "producer_surplus_diagram",
                    "minimum_price_diagram",
                    "maximum_price_diagram",
                    "production_possibility_frontier",
                    "perfect_competition_diagram",
                    "monopoly_diagram",
                    "monopsony_diagram",
                    "labour_market_diagram",
                    "payoff_matrix",
                ],
                stimulus_slots=[
                    [
                        "ped_data_table",
                        "pes_data_table",
                        "marginal_utility_table",
                        "opportunity_cost_ppc_table",
                        "elasticity_data_table",
                        "concentration_ratio_table",
                        "shutdown_cost_table",
                        "wage_rate_table",
                        "contestability_barrier_table",
                        "data_table",
                    ],
                    [
                        "ped_data_table",
                        "pes_data_table",
                        "marginal_utility_table",
                        "opportunity_cost_ppc_table",
                        "elasticity_data_table",
                        "concentration_ratio_table",
                        "shutdown_cost_table",
                        "wage_rate_table",
                        "contestability_barrier_table",
                        "data_table",
                    ],
                    [
                        "business_objective_context",
                        "minimum_wage_context",
                        "context_extract",
                        "cost_revenue_graph",
                    ],
                    [
                        "business_objective_context",
                        "xed_context",
                        "imperfect_information_context",
                        "minimum_wage_context",
                        "context_extract",
                    ],
                    [
                        "market_share_bar_chart",
                        "bar_chart",
                        "line_graph",
                        "index_number_chart",
                        "concentration_ratio_table",
                        "payoff_matrix",
                    ],
                ],
            ),
            SectionConfig(
                name="B",
                title="Data response",
                marks=50,
                answer_marks=50,
                question_marks=[5, 8, 10, 12, 15],
                command_words=["explain", "examine", "assess", "discuss", "discuss"],
            ),
            SectionConfig(
                name="C",
                title="Extended open-response choice",
                marks=25,
                answer_marks=25,
                question_marks=[25, 25],
                command_words=["evaluate", "evaluate"],
                choice_groups=[[0, 1]],
            ),
        ],
    ),
    "paper_2": PaperConfig(
        id="paper_2",
        code="9EC0/02",
        title="The National and Global Economy",
        allowed_themes={2, 4},
        duration_minutes=120,
        total_marks=100,
        sections=[
            SectionConfig(
                name="A",
                title="Multiple-choice and short-answer questions",
                marks=25,
                answer_marks=25,
                question_marks=[5, 5, 5, 5, 5],
                command_words=["mixed", "mixed", "mixed", "mixed", "mixed"],
                part_marks=[[1, 2, 2], [1, 4], [4, 1], [1, 4], [4, 1]],
                part_command_words=[
                    ["mcq", "calculate", "explain"],
                    ["mcq", "explain"],
                    ["explain", "mcq"],
                    ["mcq", "explain"],
                    ["explain", "mcq"],
                ],
                stimulus_kinds=[
                    "household_savings_line_chart",
                    "investment_line_chart",
                    "financial_market_context",
                    "development_data_table",
                    "current_account_line_chart",
                    "gdp_growth_bar_chart",
                    "unemployment_rate_bar_chart",
                    "terms_of_trade_index_chart",
                    "exchange_rate_index_chart",
                    "income_tax_schedule_table",
                    "public_spending_pie_table",
                    "labour_inactivity_context",
                    "multiplier_context",
                    "tariff_context",
                    "macro_chart",
                    "data_table",
                    "trade_cycle",
                    "context_extract",
                    "bar_chart",
                    "line_graph",
                    "index_number_chart",
                    "balance_payments_table",
                    "inflation_index_table",
                    "ad_as_diagram",
                    "keynesian_as_diagram",
                    "phillips_curve",
                    "lorenz_curve",
                    "exchange_rate_diagram",
                    "tariff_diagram",
                    "money_market_diagram",
                    "laffer_curve",
                    "poverty_trap_diagram",
                    "production_possibility_frontier",
                ],
                stimulus_slots=[
                    [
                        "household_savings_line_chart",
                        "current_account_line_chart",
                        "terms_of_trade_index_chart",
                        "exchange_rate_index_chart",
                        "line_graph",
                    ],
                    [
                        "investment_line_chart",
                        "current_account_line_chart",
                        "terms_of_trade_index_chart",
                        "exchange_rate_index_chart",
                        "line_graph",
                    ],
                    [
                        "financial_market_context",
                        "labour_inactivity_context",
                        "multiplier_context",
                        "tariff_context",
                        "context_extract",
                    ],
                    [
                        "trade_cycle",
                        "ad_as_diagram",
                        "keynesian_as_diagram",
                        "phillips_curve",
                        "lorenz_curve",
                        "exchange_rate_diagram",
                        "tariff_diagram",
                        "money_market_diagram",
                        "laffer_curve",
                        "poverty_trap_diagram",
                        "production_possibility_frontier",
                    ],
                    [
                        "tariff_context",
                        "labour_inactivity_context",
                        "context_extract",
                    ],
                ],
            ),
            SectionConfig(
                name="B",
                title="Data response",
                marks=50,
                answer_marks=50,
                question_marks=[5, 8, 10, 12, 15],
                command_words=["explain", "examine", "assess", "discuss", "discuss"],
            ),
            SectionConfig(
                name="C",
                title="Extended open-response choice",
                marks=25,
                answer_marks=25,
                question_marks=[25, 25],
                command_words=["evaluate", "evaluate"],
                choice_groups=[[0, 1]],
            ),
        ],
    ),
    "paper_3": PaperConfig(
        id="paper_3",
        code="9EC0/03",
        title="Microeconomics and Macroeconomics",
        allowed_themes={1, 2, 3, 4},
        duration_minutes=120,
        total_marks=100,
        sections=[
            SectionConfig(
                name="A",
                title="Data response",
                marks=50,
                answer_marks=50,
                question_marks=[5, 8, 12, 25, 25],
                command_words=["explain", "examine", "discuss", "evaluate", "evaluate"],
                choice_groups=[[3, 4]],
            ),
            SectionConfig(
                name="B",
                title="Data response",
                marks=50,
                answer_marks=50,
                question_marks=[5, 8, 12, 25, 25],
                command_words=["explain", "examine", "discuss", "evaluate", "evaluate"],
                choice_groups=[[3, 4]],
            ),
        ],
    ),
}


def load_builtin_paper_config(paper_id: str) -> PaperConfig:
    try:
        return deepcopy(_BUILTIN_CONFIGS[paper_id])
    except KeyError as error:
        known = ", ".join(sorted(_BUILTIN_CONFIGS))
        raise ValueError(f"Unknown paper config '{paper_id}'. Known: {known}") from error
